name: Deploy Docusaurus

on:
  push:
    branches: main

env:
  selected_node_version: 14.x
  node_options_build: --max-old-space-size=4096
  node_options_run_node_v17: --openssl-legacy-provider
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

services:
  localstack:
    image: localstack/localstack
    env:
      SERVICES: s3
      DEFAULT_REGION: ap-northeast-1
      DATA_DIR: /tmp/localstack/data
    ports: ["4566:4566"]

jobs:

  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 17.x, 16.x, 14.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: yarn
      - name: Test install
        run: |
          NODE_OPTIONS="$node_options_build" 
          yarn install --frozen-lockfile
      - name: Run code analysis
        run: |
          NODE_OPTIONS="$node_options_build"
          yarn format
      - name: Build app
        run: |
          NODE_OPTIONS="$node_options_build"
          yarn build --out-dir dist/docusaurus

      - name: Upload target version artifact
        uses: actions/upload-artifact@v2
        if: ${{matrix.node-version}} == ${{env.selected_node_version}}
        with:
          name: docs-app
          path: dist/docusaurus

  test-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@master
      with:
        name: docs-app
        path: dist/docusaurus

    - name: Configure localstack
      run: |
        aws configure set aws_access_key_id test
        aws configure set aws_secret_access_key test
        aws configure set default.region ap-northeast-1
        aws mb s3://docs-test-bucket --endpoint-url=http://localhost:4566

    - name: Deploy to AWS
      uses: reggionick/s3-deploy@v3
      with:
          folder: dist/docusaurus
          bucket: docs-test-bucket
          private: true
          noCache: true
          invalidation: /
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}