name: Docusaurus CICD

on:
  push:
    branches: "*"

env:
  selected_node_version: 14
  node_options_build: --max-old-space-size=4096
  node_options_run_node_v17: --openssl-legacy-provider

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #node-version: [ 17.x, 16.x, 14.x ]
        node-version: ${{env.selected_node_version}}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: yarn

      - name: Yarn install
        run: |
          NODE_OPTIONS="$node_options_build" 
          yarn install

      - name: Run code analysis
        run: |
          NODE_OPTIONS="$node_options_build"
          yarn format

      - name: Build app
        run: |
          NODE_OPTIONS="$node_options_build"
          yarn build --out-dir dist/docusaurus

      - name: Upload target version artifact
        uses: actions/upload-artifact@v2
        if: ${{matrix.node-version}} == ${{env.selected_node_version}}
        with:
          name: docs-app
          path: dist/docusaurus

  test-deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@master
      with:
        name: docs-app
        path: dist/docusaurus

    - uses: actions/setup-python@v2
      with:
        cache: 'pip'
        cache-dependency-path: '**/pip-requirements-ci.txt'

    - name: Configure localstack
      run: |
        # install LocalStack cli and awslocal
        pip install localstack awscli-local[ver1]
        # Make sure to pull the latest version of the image
        docker pull localstack/localstack
        # Start LocalStack in the background
        localstack start -d
        # Wait 30 seconds for the LocalStack container to become ready before timing out
        echo "Waiting for LocalStack startup..."
        localstack wait -t 30
        echo "Startup complete"
        awslocal s3 mb s3://docs-test-bucket
        awslocal s3 ls
        echo "LocalStack setup complete"

    - name: Deploy to localStack to test
      run: |
        awslocal configure set region eu-west-1
        awslocal s3 sync dist/docusaurus s3://docs-test-bucket
        awslocal s3 ls
        curl http://localhost:4566/docs-test-bucket

  deploy:
    needs: test-deploy
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to AWS when main branch gets updated
      uses: reggionick/s3-deploy@v3
      if: github.ref == 'refs/heads/main'
      with:
          folder: dist/docusaurus
          bucket: casper-docusaurus
          private: true
          noCache: true
          invalidation: /
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
