name: Docusaurus CICD

on:
  push:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      selected_node_version: 14
      node_options_build: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.selected_node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.selected_node_version }}
          cache: yarn
          
      - name: Yarn install
        run: |
          NODE_OPTIONS="$node_options_build" 
          yarn install

      - name: Run code analysis
        run: |
          NODE_OPTIONS="$node_options_build"
          yarn format

      - name: Build app
        run: |
          NODE_OPTIONS="$node_options_build"
          yarn build --out-dir dist/docusaurus

      - name: Upload target version artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs-app
          path: dist/docusaurus

      - name: Upload pip-requirements-ci.txt to be used in the test-deploy step
        uses: actions/upload-artifact@v2
        with:
          name: pip-requirements-ci
          path: .github/workflows/pip-requirements-ci.txt

  test-deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:  
    - uses: actions/download-artifact@master
      with:
        name: docs-app
        path: dist/docusaurus

    - uses: actions/download-artifact@master
      with:
        name: pip-requirements-ci

    - uses: actions/setup-python@v2
      with:
        cache: 'pip'
        cache-dependency-path: 'pip-requirements-ci.txt'

    - name: Configure localstack
      run: |
        echo "install LocalStack cli and awslocal"
        pip install localstack awscli-local[ver1]
        echo "Make sure to pull the latest version of the image"
        docker pull localstack/localstack
        echo "Start LocalStack in the background"
        localstack start -d
        #Wait 30 seconds for the LocalStack container to become ready before timing out
        echo "Waiting for LocalStack startup..."
        localstack wait -t 30
        echo "Startup complete"
        awslocal s3 mb s3://docs-test-bucket
        awslocal s3 ls 's3://docs-test-bucket'
        echo "LocalStack setup complete"

    #TODO: Investigate about replicating an AWS S3 bucket into localstack so that tests are more reliable
    - name: Deploy to localStack to test
      run: |
        awslocal s3 sync dist/docusaurus s3://docs-test-bucket/docs
        awslocal s3 ls

    - uses: bradjohnl/docs/.github/workflows/system-tests.yml
      with:
        home_url: http://localhost:4566/docs-test-bucket

    

  deploy:
    needs: system-tests
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to AWS when main branch gets updated
      uses: reggionick/s3-deploy@v3
      if: github.ref == 'refs/heads/main'
      with:
          folder: dist/docusaurus
          bucket: casper-docusaurus
          private: true
          noCache: true
          invalidation: /
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

    - uses: bradjohnl/docs/.github/workflows/system-tests.yml
      with:
        home_url: https://casper.network/docs
